Feature/nikhil backend
nikhilpalve18/UserRegistration pull request #1
Opened 2024-01-19 08:06 UTC by nikhilpalve18

2024-01-20 06:42 UTC, spreezy-tech requested changes

2024-01-25 17:51 UTC, spreezy-tech reviewed
Excellent job Nikhil on the latest suggestions. You are getting groomed the right way and I can see it in your work. Keep it up :1st_place_medal:

2024-01-27 15:05 UTC, spreezy-tech reviewed
Given couple of basic feedback and a practice scenario to help you improve understanding. Excellent work Nikhil

2024-01-29 09:28 UTC, spreezy-tech reviewed
Amazing job Nikhil. Im impressed you are able to implement suggestions with ease. Many more things we have here to learn and grow. Keep it up

2024-01-30 16:36 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/controller/UserController.java
> +            return ResponseEntity.ok("User created successfully");
That wont be neccessay. But an appropriate response with a generic response DTO will suffice the job

2024-01-30 16:39 UTC, spreezy-tech reviewed
Connect with Rohit for multi-threading suggestions. Collaborate and implement it with proper logging so it will be easier to understand for debugging.

2024-02-02 04:05 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/service/impl/UserServiceImpl.java
> +    public CompletableFuture<Void> createUser(UserRequestDTO userRequestDTO) {
Is there an explicit need for CompletableFuture everywhere?

2024-02-02 07:06 UTC, nikhilpalve18 commented on UserRegistrations/src/main/java/com/app/UserRegistration/service/impl/UserServiceImpl.java
> +    public CompletableFuture<Void> createUser(UserRequestDTO userRequestDTO) {
First I tried without using CompletableFuture then it was unable to handle exceptions properly. Completeable future has a method exceptionally which helps in handling exceptions.

2024-02-08 15:35 UTC, spreezy-tech requested changes
Excellent job Nikhil. Few comments left. Complete them and we can merge it

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/config/AsyncConfig.java
> +        threadPoolTaskExecutor.setThreadNamePrefix("MyThread: ");
Good job here. Append generated thread Id as well

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/advice/UserExceptionHandler.java
> +        methodArgumentNotValidException.getBindingResult().getFieldErrors().forEach(error->{
Remove commented code if not used

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/controller/UserController.java
> +                    Throwable cause = (ex.getCause() != null) ? ex.getCause() : ex;
If the exception is occurring in the service, does it go to controller advice or it responds from this exception section?

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/service/impl/UserServiceImpl.java
> +        userValidator.validate(userRequestDTO);
Very good

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/validation/UserValidator.java
> +                    .map(ConstraintViolation::getMessage)
Good use of map function

2024-02-08 15:35 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/validation/UserValidator.java
> +                    .map(ConstraintViolation::getMessage)
Good job for using Java 8 way of calling function

2024-02-08 17:07 UTC, nikhilpalve18 commented on UserRegistrations/src/main/java/com/app/UserRegistration/controller/UserController.java
> +                    Throwable cause = (ex.getCause() != null) ? ex.getCause() : ex;
The exception wasnt thrown to controllerAdvice it was being handled in controller itself. I reviewed the code and found that exceptionally wasnt necessary if we already have controller advice. You caught it right :)

2024-02-11 16:55 UTC, spreezy-tech requested changes
Added comment

2024-02-11 16:55 UTC, spreezy-tech commented on UserRegistrations/src/main/java/com/app/UserRegistration/service/impl/UserServiceImpl.java
> +        User user = this.userRepository.findByUsername(username);
Use Optional

2024-03-18 16:01 UTC, closed without merging